# Generated by Django 5.0.4 on 2024-06-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='menu',
            name='categoria',
            field=models.ManyToManyField(to='Crud.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(to='Crud.categoria'),
        ),
    ]
