# Generated by Django 5.0.6 on 2024-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_remove_menu_categoria_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
