# Generated by Django 5.0.6 on 2024-06-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0004_carrito_articulocarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='creado',
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='Crud.CarritoProducto', to='Crud.producto'),
        ),
        migrations.DeleteModel(
            name='ArticuloCarrito',
        ),
    ]
