# Generated by Django 5.0.4 on 2024-07-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0005_remove_carrito_creado_carritoproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
